formio/react

package.json
src/components/mixins/selectMixin.js

Just evaluate your templates using string.replace's callback... then render the html raw. (there is no need to parse it as JSX into JS)

Don't bring babel (2MB) into the client side.

---

src/components/htmlelement.jsx
src/components/index.js

1. Added the htmlelement.jsx file to the module and also added the dependancy in index file.
2. For the response of the htmlelement we don't get the "key" as a parameter in response.
3. So for each html-element key will be combination of component type(htmlelement) and index.

React-FormioRE-4 - Add HTML Element component

---

package.json
src/components/container.jsx
src/components/index.js
src/components/mixins/valueMixin.jsx

1.For that added the containers.jsx file to the module.
2.And rendered the component as per the response.

Added the implementation for the Containers.

---

src/components/index.js
src/components/selectboxes.jsx

1. Added SelectBoxes.jsx file and dependancy to the module.

Added the implementation for the Select Boxes.

---

formio.css
src/components/index.js
src/components/survey.jsx

1. Added survey.jsx file and dependency for same.
2. To complete the survey component we need to maintain the table structure of questions and answers.
3. To maintain the modularity added the generateAnswerCell function which can be written in return method itself.
4. If the user selects submit button directly, then no data will added as a parameter to submit request.

Added the implementation of the Survey component.

---

formio.css
src/components/currency.jsx
src/components/selectboxes.jsx
src/components/signature.jsx

1. Call the onChange on occurrence of onEnd event.
2. Remove the componentWillReceiveProps method form the signature component as state gets updated in value mixin.
3. Updated the background color for the first time appearance of signature board.
4. Add the span for the clear button and call the clear signature function of react-signature-pad module.
5. Update the lint issue related to select box component and for currency component.

Solve the Bug related to the  signature component

---

test/password-test.js

1. For that added the password-test.js file to the module and added the implementation for following scenarios .
1. Renders a password field.
2. Update the placeholder value.
3. Renders with a prefix.
4. Renders with a suffix.
5. Renders with prefix and suffix.
6. Sets a default value.
7. Validate renders with maxLength.
8. Validate renders with minLength.

Testcase for the password component .

---

test/checkbox-test.js

1. For that added the checkbox-test.js file to the module and added the implementation for following scenarios .
1 Renders a checkbox field.
2 Validate the checkbox with default value as a ture
3 Check the validations

Testcase for the checkbox component .

---

test/phoneNumber-test.js

1. For that added the phoneNumber-test.js file to the module and added the implementation for following scenarios .
Single phoneNumber
1. Renders a basic phoneNumber 
2. Fills in the placeholder value
3. Renders with a prefix
4. Renders with a suffix
5. Renders with prefix and suffix
6. Sets a default value
7. Sets a invalid input for single phoneNumber
8. Check single phoneNumber with required
9. Check single phoneNumber without required
10. Check single phoneNumber without label
Multiple phoneNumber
1. Renders a multi-value phoneNumber
2. Fills in the placeholder value
3. Renders with a prefix
4. Renders with a suffix
5. Renders with prefix and suffix
6. Sets a default value
7. Sets a invalid input for multiple phoneNumber
8. Adds and removes rows 
9. Check multiple phoneNumber with …

Testcase for the phoneNumber component .

---

test/survey-test.js

1. For that added the survey-test.js file to the module and added the implementation for following scenarios .
Renders a Survey field
Check the numbner of rows of survey component
Check the numbner of columns of survey component
Check the number of question labels for survey component
Check the number of anwser radio inputs for survey component

Testcase for the survey component.

---

test/content-test.js

1. For that added the content-test.js file to the module and added the implementation for following scenarios .
Renders a content component
Check the html for content component

Testcase for the content component.

---

test/button-test.js

1. For that added the button-test.js file to the module and added the implementation for following scenarios .
Renders a button component
Check the type of rendred button component
Check the theme of rendred button component
Check the size of rendred button component

Testcase for the button component.

---

lib/components/button.js
lib/components/fieldset.js
lib/components/mixins/valueMixin.js
lib/components/panel.js
lib/components/table.js
src/components/button.jsx
src/components/columns.jsx
src/components/fieldset.jsx
src/components/mixins/valueMixin.jsx
src/components/panel.jsx
src/components/table.jsx

Added custom CSS classes to components

Added custom CSS classes to components

---

test/selectboxes-test.js

1. For that added the selectboxes-test.js file to the module and added the implementation for following scenarios .
Rendered a selectboxes field
Checked the label value for each selectbox component
Checked the validations with required
Checked the validations with out required
Checked single Selectboxes with label
2. Currently selectboxes not support to inline layout. So need to add that support to the selectboxes.
3. So test case for inline layout is not implemented.
4. Please update us if we are missing out any scenario to be test.

Testcase for the selectboxes component.

---

test/hidden-test.js

1. For that added the hidden-test.js file to the module and added the implementation for following scenarios .
Renders a hidden field
Checked the attributes of the hidden input
Checked the default value of the hidden input

Testcase for the hidden component .

---

test/htmlelement-test.js

1. For that added the htmlelement-test.js file to the module and added the implementation for following scenarios .
1 Renders a basic htmlelement component.
2.Please update us if we want to write a test case for attributes of the htmlelements.

Testcase for the htmlelement component .

---

test/currency-test.js

1. For that added the currency-test.js file to the module and added the implementation for following scenarios .
Single Currency
1 Renders a basic currency
2 Fills in the placeholder value
3 Renders with a prefix
4 Renders with a suffix
5 Renders with prefix and suffix
6 Check single currency with required
7 Check single currency without required
8 Check single currency with label
9 Check single currency without label
Multiple currency
1 Renders a multi-value currency
2 Fills in the placeholder value
3 Renders with a prefix
4 Renders with a suffix
5 Renders with prefix and suffix
6 Adds and removes rows
7 Check multiple currency with required
8 Check multiple currency without required
9 Check multiple currency with label
10 Check multiple currency without label
2.Please update us if we …

Testcase for the currency component .

---

lib/components/radio.js
lib/components/selectboxes.js
src/components/radio.jsx
src/components/selectboxes.jsx

1. Selectboxes component.
2. Radio component.
For that set the inline class for particular component.

Added the support of inline layout for following component.

---

test/columns-test.js
test/forms/componentSpec.js

1. For that added the columns-test.js file to the module and added the implementation for following scenarios .
Renders a basic columns component
Check number of columns
Check the nested components of columns
4. Same changes related to the componentSpec.js file is also committed on branch
RE-52-table-component-testcase,
RE-32-container-component-testcase,
RE-54-well-component-testcase.
RE-43-panel-component-testcase
RE-39-fieldset-component-testcase

Testcase for the columns component.

---

test/fieldset-test.js
test/forms/componentSpec.js

1. For that added the fieldset-test.js file to the module and added the implementation for following scenarios .
Renders a basic fieldset component
Check with legend for fieldset component
Check without legend for fieldset component
Check the nested components of fieldset
4. Same changes related to the componentSpec.js file is also committed on branch
RE-52-table-component-testcase,
RE-32-container-component-testcase,
RE-54-well-component-testcase.
RE-43-panel-component-testcase

Testcase for the fieldset component.

---

test/forms/componentSpec.js
test/panel-test.js

1. For that added the panel-test.js file to the module and added the implementation for following scenarios .
Renders a basic panel component
Test the theme of panel component
Test the label of panel component
Check the nested components of Panel
4. Same changes related to the componentSpec.js file is also committed on branch 	
RE-52-table-component-testcase,
RE-32-container-component-testcase,
RE-54-well-component-testcase.

Testcase for the panel component.

---

test/forms/componentSpec.js
test/well-test.js

1. For that added the well-test.js file to the module and added the implementation for following scenarios .
Renders a basic well component
Check the nested components of well
4. Same changes related to the componentSpec.js file is also committed on branch RE-52-table-component-testcase and on RE-32-container-component-testcase.

Testcase for the well component.

---

test/container-test.js
test/forms/componentSpec.js

1. For that added the container-test.js file to the module and added the implementation for following scenarios .
Renders a basic container
Check the nested components of container
4. Same changes related to the componentSpec.js file is also committed on branch RE-52-table-component-testcase.

Testcase for the container component.

---

test/forms/componentSpec.js
test/table-test.js

1. For that added the table-test.js file to the module and added the implementation for following scenarios .
Renders a basic Table
Check the table classes
Check the number of rows inside table component
Check the number of columns inside table component
Check the nested components of table
2. Also added the componentSpec.js file to the module to mock the components.  

Testcase for the table component.

---

test/resource-test.js

1. For that added the resource-test.js file to the module and added the implementation for following scenarios.
Resource field
Single resource component
Renders a basic resource component
Check single resource component
Check the dropdown of resource component (85ms)
Check the by default value of the dropdown search component (56ms)
Check with label for resource component
Check without label for resource component
sets a custom class
Multiple resource component
Render multiple resource component
Check the dropdown of multiple resource component (61ms)
Check the by default value of the dropdown resource component (62ms)
Check with label for resource component
Check without label for resource component
sets a custom class

Testcase for the resource component.

---

test/signature-test.js

1. For that added the signature-test.js file to the module and added the implementation for following scenarios.
Renders a basic Signature field
Check Footer for signature component
Check refresh button of signature component
Sets a custom class

Testcase for the signature component.

---

test/datetime-test.js

1. For that added the datetime-test.js file to the module and added the implementation for following scenarios.
Renders a basic datetime field
Check with the label of DatetimePicker
Check without label of DatetimePicker
Check calendar popup window of date and time component
Check time popup window of date and time component

Testcase for the datetime component.

---

test/select-test.js

1. For that added the select-test.js file to the module and added the implementation for following scenarios.
Render a basic select component
Check the label of the select component
Check with out label for select component
Check the dropdown and check the number of options of select component
Render a multiple select component

Testcase for the select component.

---

test/address-test.js

1. For that added the address-test.js file to the module and added the implementation for following scenarios.
Single address component
Renders a basic address component
Check single addess component a basic address component
Check the dropdown of address field
Check the by default value of the dropdown search field
Insert the value inside a textfield
Multiple address component
Renders a basic address component
Check single addess component a basic address component
Check the dropdown of address field
Check the by default value of the dropdown search field
Insert the value inside a textfield
3. Currently for first occurrence of multiple address component, close button gets added to empty field.
4. Need to add an …

Testcase for the address component.

---

test/datagrid-test.js

1. For that added the datagrid-test.js file to the module and added the implementation for following scenarios .
Renders a basic datagrid
Check with label for datagrid component
Check without label for datagrid component
Check the without table classes of datagrid element
Check the with table classes of datagrid element
Check the nested components of datagrid
2. Used the component from componentSpec file to use the nested component.
3. Test case implementation for add and remove component is not implemented as both functionalities are not working properly.

Testcase for the datagrid component.

---

src/Partials/FormComponents/select.jsx

- Fixed option render issue
- Fixed option delete issue
// Outstanding issue - Form renders with blank string, in turn showing an option with 'x' and no text

Fixed render issue, and option delete bug

---

src/Partials/Components/mixins/selectMixin.jsx

- Fixed render issue
- Fixed delete string issue

Fixed multiple select resource bug

---

lib/components/FormComponents/mixins/valueMixin.js
src/components/FormComponents/mixins/valueMixin.jsx

Fixed multi select initial render with 'x' (empty string as item)

Re 77 multiselect x bug

---

README.md

Make comment about formio.js options link to said options documentation.

Update README.md to link to options

---

README.md
react-formio.d.ts
src/components/FormBuilder.js

The documentation is not up to date with the actual components.
I added vital props to FormEdit.

Documentation not up to date

---

src/components/FormBuilder.js

Replace listener's event name from "deleteComponent" to  "removeComponent"

Fix builder instance event name

---

package.json

&& instead of ; in prepublish

---

lib/components/FormioGrid.js
lib/components/Paginator.js
package-lock.json
package.json
src/components/FormioGrid.jsx
src/components/Paginator.jsx

fixes #234 
1. Added `prop-types` as production dependency
2. Ran `npx react-codemod React-PropTypes-to-prop-types src` in macOS bash shell
<details>
<summary>Output</summary>
```
npx: установлен 419 в 20.44s
? Which dialect of JavaScript do you use? JavaScript
Executing command: jscodeshift --verbose=2 --ignore-pattern=**/node_modules/** --parser babel --extensions=jsx,js --transform /Users/egor/.npm/_npx/8151/lib/node_modules/react-codemod/transforms/React-PropTypes-to-prop-types.js src
Processing 78 files...
Spawning 3 workers...
Sending 26 files to free worker...
Sending 26 files to free worker...
Sending 26 files to free worker...
SKIP src/components/FormComponents/custom.jsx
SKIP src/index.js
SKIP src/components/FormBuilder.jsx
SKIP src/components/FormComponents/datagrid.spec.js …
```

Upgrading react-formio@1.x to support React v16

---

package-lock.json
package.json

Removed extraneous recompose. It's discontinued and isn't being used for anything

removed unused recompose dependency

---

src/components/Form.jsx

fix for https://github.com/formio/react/issues/414

fix onChange triggered in loop when same submission recieved

---

src/components/FormEdit.jsx

I added Ref to html element in FORMEDIT component so the users can easily add the new options to the html node. this is so help full

Create Reference to the HTML element to add more option

---

src/components/Form.jsx

Language flag is missing, so ts-validation is failing and cannot be compiled without @ts-ignore

Added language option to form proptypes

---

Changelog.md
package.json
yarn.lock

Related to https://formio.atlassian.net/browse/FIO-7152
Updated multiple dependencies in the package.json after running `yarn upgrade-interactive`

Updated Build

---

src/components/Report.jsx
src/components/index.js

related PRs:
https://github.com/formio/ngFormio/pull/715
https://github.com/formio/angular/pull/964
https://github.com/formio/grid/pull/38
https://github.com/formio/premium/pull/247
https://github.com/formio/formio.js/pull/5081
https://github.com/formio/formio-server/pull/1254
https://github.com/formio/formio/pull/1568
https://github.com/formio/formio-app/pull/1449
https://github.com/formio/keys/pull/1
https://github.com/formio/license/pull/1
https://github.com/formio/reporting/pull/1

FIO-6493: added react wrapper for reports

---

README.md
package.json
src/components/Form.jsx
src/components/FormBuilder.jsx
src/components/FormEdit.jsx
src/components/Grid.jsx
src/components/ReactComponent.jsx
src/components/Report.jsx
src/components/SubmissionGrid.jsx
src/index.js
src/modules/auth/actions.js
src/modules/form/actions.js
src/modules/forms/actions.js
src/modules/submission/actions.js
src/modules/submissions/actions.js
src/utils.js

https://formio.atlassian.net/browse/FIO-7489
*Updated FormioJS version*

Fio 7489 formio js 5/bootstrap 5 updates to react library

---

src/components/FormBuilder.jsx
src/components/FormEdit.jsx

https://formio.atlassian.net/browse/FIO-7563
1.  Added onSaveComponent and onDeleteComponent events to the FormEdit Component
2. Added event object for onSaveComponent and onDeleteComponent events 
*https://github.com/formio/formio-apps/pull/422*

FIO-7563 added events to FormEdit Component

---

.github/pull_request_template.md

FIO-7733: type form component

---

package.json
src/components/FormGrid.tsx
yarn.lock

https://formio.atlassian.net/browse/FIO-8943
Fixes a type error and upgrades dev dependencies to latest rc versions.
n/a
n/a
n/a
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation (if applicable)
-   [x] My changes include tests that prove my fix is effective (or that my feature works as intended)
-   [x] New and existing unit/integration tests pass locally with my changes
-   [x] Any dependent changes have corresponding PRs that are listed above

FIO-8943: upgrade dev dependencies to latest rcs; fix type error

---

src/components/FormEdit.tsx

https://formio.atlassian.net/browse/FIO-9584
Removed PDF display option from the open-source.
-   [x] New and existing unit/integration tests pass locally with my changes
-   [ ] Any dependent changes have corresponding PRs that are listed above

FIO-9584: removed pdf display option from builder

---

src/components/Form.tsx

https://formio.atlassian.net/browse/FIO-9589
Before we used the instanceIsReady property as a state for the Form component. It was set to true after the formInstance is created. Once instanceIsReady was set to true, another 2 useEffect hooks attached events and set submission for this formInstance.
It worked fine in simple situation of the form rendering. In more complicated cases, when the form component is rerendered several times (e.g due to changed props), the first hook created new form instance, but another 2 hooks did not work as the instanceIsReady still was true. So, the form was rendered without events and submission attached.
The first solution that may come to the mind is to set instanceIsReady to false before to create a new formInstance, so that another 2 …

FIO-9589: fixed an issue where form does not work correctly after the react  form component rerendering

---

src/components/Form.tsx

https://formio.atlassian.net/browse/FIO-XXXX
Moved form instance cleanup to separate hook to prevent exhaustive-deps error.
_Use this section to list any dependent changes/PRs in other Form.io modules_
_Use this section to describe how you tested your changes; if you haven't included automated tests, justify your reasoning_
-   [ ] I have completed the above PR template
-   [ ] My changes generate …

refactored Form component code to prevent the exhaustive-deps error for useEffect

---

src/components/Report.jsx

https://formio.atlassian.net/browse/FIO-9413
Added catch to cover case when library license is invalid, so to set failed layout and reset report
https://github.com/formio/reporting/pull/48
Manually with valid/invalid library license keys
-   [ ] My changes include tests that prove my fix is effective (or that …

FIO-9413: Fix library license check

---

src/components/SubmissionGrid.tsx

https://formio.atlassian.net/browse/FIO-9678
Before, toString method returned undefined for number type. This PR fixes it.
-   [x] New and existing unit/integration tests pass locally with my changes
-   [ ] Any dependent changes have corresponding PRs that are listed above

FIO-9678: fixed an issue where number value is not displayed is submission grid
