package.json
src/app.js
src/components/mixins/selectMixin.js

I should have split this into two, but I was already deep in when I noticed the strict mode bug.
I wanted to jump in and update react for you. So this primarily does that.
However, my previous pull request had a hidden bug because all modules are marked strict by default. There is a fix for that in here as well.  Once this pull request is merged, I recommend checking out the tag v0.3.0 and testing it through your stack and then publishing it to npm. Then cut a 0.4.0 with the react updates.
The react updates permit React 0.14 and 15.x versions. Giving your component widest possible user base. For projects suck on 0.13 they can continue to use <=0.3 of this component.

Update React & one fix

---

src/components/columns.jsx

- In order to reflect bootstrap deprecations in their grid system, i've
changed the classname from col-xs-6 to col-sm-6, also, the angular app
uses this class.

Change the column classname to reflect deprecation

---

test/email-test.js

1. For that added the email-test.js file to the module and added the implementation for following scenarios .
Single email
Renders a basic email
Fills in the placeholder value
Renders with a prefix
Renders with a suffix
Renders with prefix and suffix
Sets a default value
Check single email with required
Check single email without required
Check single email without label
Multiple email
Renders a multi-value email
Fills in the placeholder value
Renders with a prefix
Renders with a suffix
Renders with prefix and suffix
Adds and removes rows (341ms)
Check multiple email with required
Check multiple email without required
Check multiple email without label

Testcase for the email component .

---

test/textarea-test.js

1. For that added the Textarea-test.js file to the module and added the implementation for following scenarios .
Single Textarea
1 Renders a basic textarea
2 Fills in the placeholder value
3 Renders with a prefix
4 Renders with a suffix
5 Renders with prefix and suffix
6 Check single textarea with required
7 Check single textarea without required
8 Check single textarea without label
Multiple Textarea
1 Renders a multi-value textarea
2 Fills in the placeholder value
3 Renders with a prefix
4 Renders with a suffix
5 Renders with prefix and suffix
6 Adds and removes rows
7 Check multiple textarea with required
8 Check multiple textarea without required
9 Check multiple textarea without label

Testcase for the Textarea component .

---

test/radio-test.js

1. For that added the radio-test.js file to the module and added the implementation for following scenarios .
Renders a radio field
Check the label value for each radio component
Check radio component with label
Check the validations with required
Check the validations without required

Testcase for the radio component.

---

src/components/FormComponents/mixins/componentMixin.jsx

In cases where form values do not change, but the pristineness does (for example, when the form is submitted without any modifications to the fields), the form components would not update to show any validation errors. This is now corrected with this fix.

Enable component update when isPristine changes

---

package.json
src/components/Formio.js

Ran into a problem where react-formio causes reference to undefined `this.formio` object when applying submission object while formio is being constructed.
Associated pull request will address the issue and enable update of submission during form creation phase.

Allow adjusting submission while form is being created

---

src/components/FormBuilder.jsx

The `FormioFormBuilder` constructor mutates the `form` prop passed to it as components are added. This PR clones props before initializing the builder.
It's a bad idea to mutate props to begin with (they're supposed to be immutable). It is also responsible for https://github.com/formio/react-formio/issues/208, https://github.com/formio/react-formio/pull/222, https://github.com/formio/react-formio/issues/228, because line 65 compares `nextProps` to the mutated props rather than the initial props. As a result, nearly anytime `componentWillReceiveProps` fires, it will initialize a new builder. 
This PR should resolve the dragula error. However, there is remaining unexpected behavior related to handling updated props that this PR does _not_ fix. For instance, if you add a form component and …

Don't mutate props

---

src/modules/submissions/actions.js

Fixes #242 by allowing to configure some 'static' parts of the query
when initialising the store and some 'dynamic' parts during dispatch
of `getSubmissions`.

Combine the query in store with getSubmissions argument

---

src/components/FormBuilder.jsx

The previous attempt (#216) to fix #198 is being overwritten in fad22d8be15291a7a27a9bf8ca386c1da0caa4ba.
In addition to #216, this PR also fixes `onDeleteComponent` not being called.

Fix FormBuilder's onChange and onDeleteComponent not being called

---

.gitignore
src/components/FormBuilder.jsx

When we edit an existing form, all props set for each components are removed (for example id is strip from component).
It comes an unexpected behavior when we use component.id as key (react component) to generate form in application.
Before fix:
```json
{
"_id": "5d64f2e52326671f40b5b763",
"type": "form",
"tags": [
"common"
],
"owner": "5d2b606ed82bbfbdb5026c6d",
"components": [
{
"label": "Text Field",
"key": "textField",
}
```
after fix:
```jsonc
{
"_id": "5d64f2e52326671f40b5b763",
"type": "form",
"tags": [
"common"
],
"owner": "5d2b606ed82bbfbdb5026c6d",
"components": [
{
"label": "Text Field",
"labelPosition": "top",
"placeholder": "",
"description": "",
"tooltip": "",
"prefix": "",
"suffix": "",
"widget": {
"type": "input"
},
"inputMask": "",
"allowMultipleMasks": false,
// etc... …
```

fix: Retrieve component props when form change

---

package.json
src/components/Errors.jsx
src/components/Form.jsx
src/components/FormBuilder.jsx
src/types.js
src/utils.js
tsconfig.json

Add Typescript typings to build, and push to the lib folder for inclusion in the published package.
- Add "build-types" script to packages.json , and run as part of the prepublish script.
- Add Jsdoc types to Form.jsx to provide stronger typedef.
Relates to #184

feat: Typescript typings 

---

src/components/ReactComponent.tsx

`all` was getting lost in ReactComponent.destroy()

Handle destroy(all) in ReactComponent

---

README.md

Fixing typo in `<FormBuilder />` example

fix: README typo in examples 

---

Changelog.md
src/components/FormEdit.jsx

Pretty basic update, but currently the saveText prop defaults to '' and is not a valid prop in typescript.  This causes typescript to complain.
```
Property 'saveText' does not exist on type 'IntrinsicAttributes & Pick<InferProps<typeof propTypes>, "options" | "builder" | "onSave"> & InexactPartial<Pick<InferProps<typeof propTypes>, "form">> & InexactPartial<...>'
```
This adds the prop `saveText` to the proptypes object for the FormEdit component.
I would argue that this prop should be required since the default value is an empty string but that is something that could be discussed as a follow on to this PR.
This also replaces the `onSave` proptype with `saveForm`, since `onSave` is not found anywhere in the code for that component whereas `saveForm` is used but isn't defined in the …

Added missing proptype (saveText, saveForm) for FormEdit

---

src/components/Form.jsx

https://formio.atlassian.net/browse/FIO-4301
https://formio.atlassian.net/browse/FIO-4302
Since react updates state asynchroniously, there were cases when after calling createWebformInstance and setting a new webform instance using setFormio(instance), the formio property was still containg an old instance of the webform which was causing incorrect behaviour.

FIO-4301/4302: Fixes an issue where for is being set to the old formioInstance after recreating it

---

README.md
src/components/FormEdit.jsx
src/components/ReactComponent.jsx

Hi there, I was just passing through and noticed a few possible tweaks. I don't see a CONTRIBUTING.md so I just went with it. Hope this helps!
Changes:
* Updated the README.md to better reflect the usage of the `Form` component and fixed a typo. It was not immediately obvious as a first-time reader what the differences are between `src`, `form`, and `url`. 
* Minor whitespace and lint style fixes in `FormEdit.jsx` and `ReactComponent.jsx`.

Documentation and formatting cleanup

---

CONTRIBUTING.md

This CONTRIBUTING.md file will help our fellow contributors to show by which mens they can contribute to this project

Asserting CONTRIBUTING guidelines.

---

src/components/FormEdit.tsx

https://formio.atlassian.net/browse/FIO-9590
https://formio.atlassian.net/browse/FIO-9575
Added catch for api errors regarding form settings and rendered error component to show them to the user.
None
Manually 
-   [ ] My changes include tests that prove my fix is effective (or that my feature works as …

FIO-9590 | FIO-9575: Show api validation errors for form settings block

---

src/components/FormBuilder.tsx
src/components/FormEdit.tsx

https://formio.atlassian.net/browse/FIO-9592
Added submit button to initial form and subscribed to setDisplay renderer event to update the form definition (fixes submit button addition/removal when switching to Wizard form type and back)
formio/formio.js/pull/5984
Manually
-   [ ] My changes include tests …

FIO-9592: Fix default submit button

---

src/components/Form.tsx

https://formio.atlassian.net/browse/FIO-XXXX
- store form json in refs and compare it with current props to define if the instance should be recreated
- use the same callback reference to on and off events
-   [ ] I have completed the above PR template
-   [ ] My changes generate no new warnings
-   [ ] New and existing unit/integration tests pass locally with my changes
-   [ ] Any dependent changes have corresponding PRs that are listed above

do not recreate form instance if the form json is not changed deeply

---

src/hooks/usePagination.tsx

https://formio.atlassian.net/browse/FIO-9671
Updated behavior of "Next" pagination button:
When checking for presence items to load (hasMore) added calculation considering the amount of items on the server (serverCount).
-
manually
-   [ ] My changes generate no new warnings
-   [ ] New and existing unit/integration tests pass locally with my changes
-   [x] Any dependent changes have corresponding PRs that are listed above

FIO-9671: fix Next pagination button

---

README.md
package.json
src/components/FormEdit.tsx
src/components/FormGrid.tsx
src/components/__tests__/Form.test.tsx
src/hooks/__tests__/usePagination.test.ts
tsconfig.json
yarn.lock

https://formio.atlassian.net/browse/FIO-9881
upgrated up to React19, Formio/js upadated to latest realised version
manually using React19 app 
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] New and existing unit/integration tests pass locally with my changes
-   [ ] Any dependent changes have corresponding PRs that are listed above

FIO-9881: upgrated up to React19

---

src/components/Form.tsx

https://formio.atlassian.net/browse/FIO-9944
We need to destroy existing form instance each time we set it or there will be some cases when the new form instance is set before the previouse one got destroyed to prevent the memory leak.
_Use this section to list any dependent changes/PRs in other Form.io modules_
_Use this section to describe how you tested your changes; if you haven't included automated tests, justify your reasoning_
-   [ ] I have completed the above PR template
-   [ ] I …

FIO-9944: Fixes an issue where some form instances will not be destroyed

---

README.md

https://formio.atlassian.net/browse/FIO-XXXX
_Use this section to provide a summary description of the changes you've made_
_Use this section to list any dependent changes/PRs in other Form.io modules_
_Use this section to describe how you tested your changes; if you haven't included automated tests, justify your reasoning_
-   [ ] I have completed the above PR template
-   [ ] My changes generate …

React Compatibility Matrix
